In [2]:
import csv 
import pandas as pd
#read CSV files that contain pandemic data 
COVID_data = pd.read_csv("data_sets/COVID-19.csv") 
COVID_data
COVID_data.loc[COVID_data['iso_code'] == 'EGY']

#5 countries of focus
#AP= US, Australia    ZL= China, Russia  JB= UK, EGY

#Clean COVID-19 DataFrame and extract data based on location, date, total_cases, and total_deaths
#Create new COVID-19 DataFrame
#Multiple Line graph for date and total_cases for each country
#Line graph for date and total deaths for each country

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,...,aged_70_older,gdp_per_capita,extreme_poverty,cvd_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy
8070,EGY,Africa,Egypt,2019-12-31,0.0,0.0,0.0,0.0,0.000,0.000,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
8071,EGY,Africa,Egypt,2020-01-01,0.0,0.0,0.0,0.0,0.000,0.000,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
8072,EGY,Africa,Egypt,2020-01-02,0.0,0.0,0.0,0.0,0.000,0.000,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
8073,EGY,Africa,Egypt,2020-01-03,0.0,0.0,0.0,0.0,0.000,0.000,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
8074,EGY,Africa,Egypt,2020-01-04,0.0,0.0,0.0,0.0,0.000,0.000,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8255,EGY,Africa,Egypt,2020-07-07,76222.0,969.0,3422.0,79.0,744.833,9.469,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
8256,EGY,Africa,Egypt,2020-07-08,77279.0,1057.0,3489.0,67.0,755.161,10.329,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
8257,EGY,Africa,Egypt,2020-07-09,78304.0,1025.0,3564.0,75.0,765.178,10.016,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
8258,EGY,Africa,Egypt,2020-07-10,79254.0,950.0,3617.0,53.0,774.461,9.283,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99
8259,EGY,Africa,Egypt,2020-07-11,80235.0,981.0,3702.0,85.0,784.047,9.586,...,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,89.827,1.6,71.99

In [ ]:
#LOCATING COVID DATA
#COVID_data.loc[COVID_data['iso_code'] == 'USA']
# COVID_data.loc[COVID_data['iso_code'] == 'AUS']
# COVID_data.loc[COVID_data['iso_code'] == 'MEX']
#COVID_data.loc[COVID_data['iso_code'] == 'UK']#No UK
#COVID_data.loc[COVID_data['iso_code'] == 'CHL'] 
#COVID_data.loc[COVID_data['iso_code'] == 'CAN']

In [ ]:
##COVID-19 Do more cases= more deaths?
# plot scatter plot and linear regression for each country Cases x, Deaths y

In [ ]:
#Clean H1N1 DataFrame and extract data based on location, date, total_cases, and total_deaths
#Create new H1N1 DataFrame
# Line graph for Update Time and Cases for each country
#Line graph for date and total Deaths for each country

In [ ]:
##H1N1 Do more cases= more deaths?
# plot scatter plot and linear regression for each country Cases x, Deaths y

In [ ]:
## Which country has the most cases for each pandemic?

In [ ]:


##Hypothesis: Covid-19 will have a higher transmition rate than H1N1. 

# Independent T-test

In [ ]:
#Do more cases= more deaths based on age